#MySQL Configuration:
db.connection.url=jdbc:mysql://localhost/dbNautilus
db.connection.username=root
db.connection.password=admin
#-------------------------------------------------------------------------------
